
export  const equipmentListUtils =[
     {
       department: "Cementing",
       equipmentName: "Cement Unit",
       equipmentType: "JEREH",
       equipmentSerialNumber : "03220016",
       location:"Base",
       equipmentCodeName:"06",
     },
    {
       department: "Cementing",
       equipmentName: "Cement Unit",
       equipmentType: "JEREH",
       equipmentSerialNumber : "00300016",
       location:"Base",
       equipmentCodeName:"cementUnit03",
    },
    {
      department: "Cementing",
      equipmentName: "Cement Unit",
      equipmentType: "SCHLUMBERGER",
      equipmentSerialNumber : "02",
      location:"Base",
      equipmentCodeName:"cementUnit02",
    },
    {
      department: "Cementing",
      equipmentName: "Cement Unit",
      equipmentType: "SCHLUMBERGER",
      equipmentSerialNumber : "04",
      location:"Base",
      equipmentCodeName:"cementUnit04",
    },
    {
      department: "Cementing",
      equipmentName: "Cement Unit",
      equipmentType: "SCHLUMBERGER",
      equipmentSerialNumber : "05",
      location:"Base",
      equipmentCodeName:"cementUnit05",
    },
    {
      department: "Cementing",
      equipmentName: "120bbl BatchMixer",
      equipmentType: "SCHLUMBERGER",
      equipmentSerialNumber : "01",
      location:"Base",
      equipmentCodeName:"cementUnit01",
    },
  ]


  export const equipmentInventoryListUtils =[
     
    {
      department: "Cementing",
      equipment: "Cement Unit",
      type: "JEREH",
      serialNumber : "00300016",
      category: "in",
      location:"Base",
      code:"cementUnit03",
      item : "10ft Chiksan",
      tag: "CUT-03 1234",
    },
    {
      department: "Cementing",
      equipment: "Cement Unit",
      type: "JEREH",
      serialNumber : "CUT-03 10ft 77756466",
      category: "in",
      location:"Base",
      code:"cementUnit03",
      item : "10ft Chiksan",
      tag: "CUT-03 123467",
    },
    {
      department: "Cementing",
      equipment: "Cement Unit",
      type: "JEREH",
      serialNumber : "CUT-03 10ft 77756467",
      category: "in",
      location:"Base",
      code:"cementUnit03",
      item : "10ft Chiksan",
      tag: "CUT-03 1234675",
    },
    {
      department: "Cementing",
      equipment: "Cement Unit",
      type: "JEREH",
      serialNumber : "00300013",
      category: "out",
      location:"Base",
      code:"cementUnit06",
      item : "10ft Chiksan",
      tag: "CUT-06 2234675",
    },
    {
      department: "Cementing",
      equipment: "Cement Unit",
      type: "JEREH",
      serialNumber : "00300013",
      category: "out",
      location:"Base",
      code:"cementUnit03",
      item : "2x2 inch plug valve",
      tag: "CUT-06 2234675",
    },
    {
      department: "Cementing",
      equipment: "Cement Unit",
      type: "SCHLUMBERGER",
      serialNumber : "02",
      category: "in",
      location:"Base",
      code:"cementUnit02",
      item : "2-way Swivel",
      tag: "CUT-02 2234675",
    },
    {
      department: "Cementing",
      equipment: "Cement Unit",
      type: "SCHLUMBERGER",
      serialNumber : "04",
      category: "out",
      location:"Base",
      code:"cementUnit04",
      item : "2-way Swivel",
      tag: "CUT-04 2234675",
    },
    {
      department: "Cementing",
      equipment: "Cement Unit",
      type: "SCHLUMBERGER",
      serialNumber : "05",
      category: "out",
      location:"Base",
      code:"cementUnit05",
      item : "10ft Chiksan",
      tag: "CUT-05 2234675",
    },
    {
      department: "Cementing",
      equipment: "120bbl BatchMixer",
      type: "SCHLUMBERGER",
      serialNumber : "01",
      category: "in",
      location:"Base",
      code:"cementUnit01",
      item : "2x2 Plug Valve",
      tag: "CUT-01 2234675",
    },
  ];
